export const GAME_SYMBOLS = {
  ZERO: 'ZERO',
  CROSS: 'CROSS',
  TRIGLE: 'TRINGLE',
  SQUARE: 'SQUARE',
}

export const MOVE_ORDER = [
  GAME_SYMBOLS.CROSS,
  GAME_SYMBOLS.ZERO,
  GAME_SYMBOLS.TRIGLE,
  GAME_SYMBOLS.SQUARE,
]